// <auto-generated />
using System;
using HBSort.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HBSort.Core.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20260513151244_AddStorageBinKind")]
    partial class AddStorageBinKind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("HBSort.Core.Models.DailyStats", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinifigsCompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinifigsDismantledCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("DailyStats");
                });

            modelBuilder.Entity("HBSort.Core.Models.FloatingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrickognizeCategory")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginMinifigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageBinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginMinifigId");

                    b.HasIndex("StorageBinId");

                    b.HasIndex("PartNumber", "ColorId");

                    b.ToTable("FloatingParts");
                });

            modelBuilder.Entity("HBSort.Core.Models.ScanEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognizedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasUndone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanEvents");
                });

            modelBuilder.Entity("HBSort.Core.Models.StorageBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("StorageBins");
                });

            modelBuilder.Entity("HBSort.Core.Models.TrackedMinifig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BricklinkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FigNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageBinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageBinId");

                    b.ToTable("TrackedMinifigs");
                });

            modelBuilder.Entity("HBSort.Core.Models.TrackedMinifigPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackedMinifigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackedMinifigId");

                    b.ToTable("TrackedMinifigParts");
                });

            modelBuilder.Entity("HBSort.Core.Models.FloatingPart", b =>
                {
                    b.HasOne("HBSort.Core.Models.TrackedMinifig", "OriginMinifig")
                        .WithMany()
                        .HasForeignKey("OriginMinifigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HBSort.Core.Models.StorageBin", "StorageBin")
                        .WithMany("FloatingParts")
                        .HasForeignKey("StorageBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginMinifig");

                    b.Navigation("StorageBin");
                });

            modelBuilder.Entity("HBSort.Core.Models.TrackedMinifig", b =>
                {
                    b.HasOne("HBSort.Core.Models.StorageBin", "StorageBin")
                        .WithMany("TrackedMinifigs")
                        .HasForeignKey("StorageBinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageBin");
                });

            modelBuilder.Entity("HBSort.Core.Models.TrackedMinifigPart", b =>
                {
                    b.HasOne("HBSort.Core.Models.TrackedMinifig", "TrackedMinifig")
                        .WithMany("RequiredParts")
                        .HasForeignKey("TrackedMinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedMinifig");
                });

            modelBuilder.Entity("HBSort.Core.Models.StorageBin", b =>
                {
                    b.Navigation("FloatingParts");

                    b.Navigation("TrackedMinifigs");
                });

            modelBuilder.Entity("HBSort.Core.Models.TrackedMinifig", b =>
                {
                    b.Navigation("RequiredParts");
                });
#pragma warning restore 612, 618
        }
    }
}
