// <auto-generated />
using System;
using LegoMinifigSorter.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoMinifigSorter.Core.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20260501024314_AddBricklinkColorId")]
    partial class AddBricklinkColorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.DailyStats", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinifigsCompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinifigsDismantledCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("DailyStats");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.FloatingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BricklinkColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageBinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StorageBinId");

                    b.ToTable("FloatingParts");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.ScanEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognizedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasUndone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanEvents");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.StorageBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageBins");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.TrackedMinifig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BricklinkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FigNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageBinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageBinId");

                    b.ToTable("TrackedMinifigs");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.TrackedMinifigPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BricklinkColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackedMinifigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackedMinifigId");

                    b.ToTable("TrackedMinifigParts");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.FloatingPart", b =>
                {
                    b.HasOne("LegoMinifigSorter.Core.Models.StorageBin", "StorageBin")
                        .WithMany("FloatingParts")
                        .HasForeignKey("StorageBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageBin");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.TrackedMinifig", b =>
                {
                    b.HasOne("LegoMinifigSorter.Core.Models.StorageBin", "StorageBin")
                        .WithMany("TrackedMinifigs")
                        .HasForeignKey("StorageBinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageBin");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.TrackedMinifigPart", b =>
                {
                    b.HasOne("LegoMinifigSorter.Core.Models.TrackedMinifig", "TrackedMinifig")
                        .WithMany("RequiredParts")
                        .HasForeignKey("TrackedMinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedMinifig");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.StorageBin", b =>
                {
                    b.Navigation("FloatingParts");

                    b.Navigation("TrackedMinifigs");
                });

            modelBuilder.Entity("LegoMinifigSorter.Core.Models.TrackedMinifig", b =>
                {
                    b.Navigation("RequiredParts");
                });
#pragma warning restore 612, 618
        }
    }
}
