// <auto-generated>
// Diese Datei wird vom Tool HBSort.SetupTools generiert.
// Letzter Stand: 2026-05-01
// Quelle: https://rebrickable.com/colors/
// Anzahl Farben: 271, davon mit BrickLink-Mapping: 178
// Manuelle Aenderungen werden beim naechsten Generieren ueberschrieben.
// </auto-generated>
#nullable enable

using System.Collections.Generic;

namespace HBSort.Core.Services;

/// <summary>
/// Mapping zwischen Rebrickable-, BrickLink- und BrickOwl-Farb-IDs.
/// Wichtig: Die drei Plattformen verwenden unterschiedliche IDs fuer dieselben Farben.
/// </summary>
public static class ColorMapping
{
    /// <summary>
    /// Mapping Rebrickable-ID -> BrickLink-ID. Null wenn keine BL-Entsprechung existiert.
    /// </summary>
    public static readonly IReadOnlyDictionary<int, int?> RebrickableToBricklink = new Dictionary<int, int?>
    {
        { 320, 59 }, // Dark Red -> BL: Dark Red
        { 1113, null }, // HO Dark Red -> kein BL-Mapping
        { 100, 26 }, // Light Salmon -> BL: Light Salmon
        { 77, 77 }, // Light Pink -> BL: Light_Pink
        { 1037, null }, // Modulex Violet -> kein BL-Mapping
        { 1146, 175 }, // Warm Pink -> BL: Warm Pink
        { 1087, null }, // Duplo Pink -> kein BL-Mapping
        { 1069, 252 }, // Pearl Red -> BL: Pearl Red
        { 13, 23 }, // Pink -> BL: Pink
        { 1102, null }, // Trans-Neon Red -> kein BL-Mapping
        { 1050, 220 }, // Coral -> BL: Coral
        { 351, 94 }, // Medium Dark Pink -> BL: Medium Dark Pink
        { 1038, null }, // Modulex Pink -> kein BL-Mapping
        { 114, 100 }, // Glitter Trans-Dark Pink -> BL: Glitter Trans-Dark Pink
        { 45, 50 }, // Trans-Dark Pink -> BL: Trans-Dark Pink
        { 1082, null }, // Clikits Pink -> kein BL-Mapping
        { 69, 93 }, // Light Purple -> BL: Light Purple
        { 29, 104 }, // Bright Pink -> BL: Bright Pink
        { 230, 107 }, // Trans-Pink -> BL: Trans-Pink
        { 1099, null }, // Glitter Trans-Pink -> kein BL-Mapping
        { 5, 47 }, // Dark Pink -> BL: Dark Pink
        { 1054, 224 }, // Opal Trans-Dark Pink -> BL: Satin Trans-Dark Pink
        { 26, 71 }, // Magenta -> BL: Magenta
        { 63, 114 }, // Chrome Pink -> BL: Chrome Pink
        { 22, 24 }, // Purple -> BL: Purple
        { 373, 54 }, // Sand Purple -> BL: Sand Purple
        { 1007, 227 }, // Reddish Lilac -> BL: Clikits Lavender
        { 236, 284 }, // Trans-Light Purple -> BL: Trans_Light_Purple
        { 30, 157 }, // Medium Lavender -> BL: Medium Lavender
        { 1059, 230 }, // Opal Trans-Purple -> BL: Satin Trans-Purple
        { 1046, null }, // Modulex Foil Violet -> kein BL-Mapping
        { 31, 154 }, // Lavender -> BL: Lavender
        { 1101, null }, // Duplo Dark Purple -> kein BL-Mapping
        { 1097, null }, // Glitter Trans-Medium Purple -> kein BL-Mapping
        { 1094, 107 }, // Trans-Medium Purple -> BL: Transparent Purple
        { 1018, null }, // Modulex Black -> kein BL-Mapping
        { 85, 89 }, // Dark Purple -> BL: Dark Purple
        { 1001, 112 }, // Medium Violet -> BL: Medium_Violet
        { 129, 102 }, // Glitter Trans-Purple -> BL: Glitter Trans-Purple
        { 52, 51 }, // Trans-Purple -> BL: Trans-Purple
        { 20, 44 }, // Light Violet -> BL: Light Violet
        { 1147, 174 }, // Blue Violet -> BL: Blue Violet
        { 1093, 16 }, // Light Lilac -> BL: Light Violet
        { 23, 109 }, // Dark Blue-Violet -> BL: Dark Blue-Violet
        { 112, 73 }, // Medium Bluish Violet -> BL: Medium Violet
        { 89, 97 }, // Royal Blue -> BL: Royal Blue
        { 1061, 232 }, // Opal Trans-Dark Blue -> BL: Satin Trans-Dark Blue
        { 33, 14 }, // Trans-Dark Blue -> BL: Trans-Dark Blue
        { 110, 43 }, // Violet -> BL: Violet
        { 1014, null }, // Modulex Light Bluish Gray -> kein BL-Mapping
        { 1073, 244 }, // Pearl Black -> BL: Pearl Black
        { 379, 55 }, // Sand Blue -> BL: Sand Blue
        { 137, 78 }, // Pearl Sand Blue -> BL: Pearl Sand Blue
        { 1123, null }, // HO Medium Blue -> kein BL-Mapping
        { 1, 7 }, // Blue -> BL: Blue
        { 73, 42 }, // Medium Blue -> BL: Medium Blue
        { 272, 63 }, // Dark Blue -> BL: Dark Blue
        { 1109, null }, // HO Dark Blue -> kein BL-Mapping
        { 1006, 163 }, // Trans-Light Royal Blue -> BL: Transparent Light Royal Blue
        { 143, 74 }, // Trans-Medium Blue -> BL: Trans-Medium Blue
        { 1035, null }, // Modulex Medium Blue -> kein BL-Mapping
        { 1131, null }, // HO Sand Blue -> kein BL-Mapping
        { 212, 105 }, // Bright Light Blue -> BL: Bright Light Blue
        { 1034, null }, // Modulex Tile Blue -> kein BL-Mapping
        { 1044, null }, // Modulex Foil Dark Blue -> kein BL-Mapping
        { 61, 112 }, // Chrome Blue -> BL: Chrome Blue
        { 1070, 254 }, // Pearl Blue -> BL: Pearl Blue
        { 9, 62 }, // Light Blue -> BL: Light Blue
        { 43, 113 }, // Trans-Very Lt Blue -> BL: Trans-Aqua
        { 313, 71 }, // Maersk Blue -> BL: Maersk Blue
        { 1128, null }, // HO Metallic Sand Blue -> kein BL-Mapping
        { 321, 153 }, // Dark Azure -> BL: Dark Azure
        { 1105, null }, // HO Azure -> kein BL-Mapping
        { 1125, null }, // HO Metallic Blue -> kein BL-Mapping
        { 1045, null }, // Modulex Foil Light Blue -> kein BL-Mapping
        { 1036, null }, // Modulex Pastel Blue -> kein BL-Mapping
        { 1107, null }, // HO Cyan -> kein BL-Mapping
        { 1033, null }, // Modulex Teal Blue -> kein BL-Mapping
        { 232, 87 }, // Sky Blue -> BL: Sky Blue
        { 1106, null }, // HO Blue-gray -> kein BL-Mapping
        { 1075, null }, // Duplo Medium Blue -> kein BL-Mapping
        { 1074, null }, // Duplo Blue -> kein BL-Mapping
        { 1008, null }, // Vintage Blue -> kein BL-Mapping
        { 1051, 71 }, // Pastel Blue -> BL: Maersk Blue
        { 322, 156 }, // Medium Azure -> BL: Medium Azure
        { 11, 40 }, // Light Turquoise -> BL: Light Turquoise
        { 1003, 162 }, // Glitter Trans-Light Blue -> BL: Glitter Trans-Light Blue
        { 1053, 223 }, // Opal Trans-Light Blue -> BL: Satin Trans-Light Blue
        { 3, 39 }, // Dark Turquoise -> BL: Dark Turquoise
        { 1115, null }, // HO Dark Turquoise -> kein BL-Mapping
        { 41, 15 }, // Trans-Light Blue -> BL: Trans-Light Blue
        { 1032, null }, // Modulex Aqua Green -> kein BL-Mapping
        { 323, 152 }, // Light Aqua -> BL: Light Aqua
        { 1104, null }, // HO Aqua -> kein BL-Mapping
        { 118, 41 }, // Aqua -> BL: Aqua
        { 1090, null }, // Duplo Turquoise -> kein BL-Mapping
        { 1108, null }, // HO Dark Aqua -> kein BL-Mapping
        { 1118, null }, // HO Light Aqua -> kein BL-Mapping
        { 1111, null }, // HO Dark Green -> kein BL-Mapping
        { 288, 80 }, // Dark Green -> BL: Dark Green
        { 62, 113 }, // Chrome Green -> BL: Chrome Green
        { 74, 37 }, // Medium Green -> BL: Medium Green
        { 1071, 253 }, // Pearl Green -> BL: Pearl Green
        { 378, 48 }, // Sand Green -> BL: Sand Green
        { 1132, null }, // HO Sand Green -> kein BL-Mapping
        { 1078, null }, // Duplo Medium Green -> kein BL-Mapping
        { 2, 6 }, // Green -> BL: Green
        { 1058, 221 }, // Trans-Light Green -> BL: Trans-Light Green
        { 1079, null }, // Duplo Light Green -> kein BL-Mapping
        { 1098, null }, // Glitter Trans-Green -> kein BL-Mapping
        { 34, 20 }, // Trans-Green -> BL: Trans-Green
        { 1060, 233 }, // Opal Trans-Bright Green -> BL: Satin Trans-Bright Green
        { 1042, null }, // Modulex Foil Dark Green -> kein BL-Mapping
        { 1009, null }, // Vintage Green -> kein BL-Mapping
        { 1077, 248 }, // Fabuland Lime -> BL: Fabuland Lime
        { 1114, null }, // HO Dark Sand Green -> kein BL-Mapping
        { 10, 36 }, // Bright Green -> BL: Bright Green
        { 17, 38 }, // Light Green -> BL: Light Green
        { 1043, null }, // Modulex Foil Light Green -> kein BL-Mapping
        { 1030, null }, // Modulex Pastel Green -> kein BL-Mapping
        { 294, 118 }, // Glow In Dark Trans -> BL: Glow In Dark Trans
        { 1127, null }, // HO Metallic Green -> kein BL-Mapping
        { 76, 117 }, // Speckle DBGray-Silver -> BL: Speckle DBGray-Silver
        { 1031, null }, // Modulex Olive Green -> kein BL-Mapping
        { 1057, 226 }, // Trans-Light Bright Green -> BL: Trans-Light Bright Green
        { 1086, 125 }, // Pearl Lime -> BL: Metallic Green
        { 81, 125 }, // Metallic Green -> BL: Metallic Green
        { 1002, 163 }, // Glitter Trans-Neon Green -> BL: Glitter Trans-Neon Green
        { 1141, null }, // Neon Green -> kein BL-Mapping
        { 27, 34 }, // Lime -> BL: Lime
        { 158, 158 }, // Yellowish Green -> BL: Yellowish Green
        { 120, 35 }, // Light Lime -> BL: Light Lime
        { 35, 108 }, // Trans-Bright Green -> BL: Trans-Bright Green
        { 115, 76 }, // Medium Lime -> BL: Medium Lime
        { 1122, null }, // HO Light Yellow -> kein BL-Mapping
        { 1029, null }, // Modulex Lemon -> kein BL-Mapping
        { 1112, null }, // HO Dark Lime -> kein BL-Mapping
        { 1110, null }, // HO Dark Gray -> kein BL-Mapping
        { 1129, null }, // HO Olive Green -> kein BL-Mapping
        { 326, 155 }, // Olive Green -> BL: Olive Green
        { 1142, null }, // Dark Olive Green -> kein BL-Mapping
        { 1076, 67 }, // Duplo Lime -> BL: Light Lime
        { 42, 16 }, // Trans-Neon Green -> BL: Trans-Neon Green
        { 1062, 236 }, // Vibrant Yellow -> BL: Neon Yellow
        { 226, 103 }, // Bright Light Yellow -> BL: Bright Light Yellow
        { 1121, null }, // HO Light Tan -> kein BL-Mapping
        { 334, 21 }, // Chrome Gold -> BL: Chrome Gold
        { 1005, 162 }, // Trans-Fire Yellow -> BL: Transparent Fire Yellow
        { 54, 121 }, // Trans-Neon Yellow -> BL: Trans-Neon Yellow
        { 1011, null }, // Vintage Yellow -> kein BL-Mapping
        { 1100, null }, // Clikits Yellow -> kein BL-Mapping
        { 46, 19 }, // Trans-Yellow -> BL: Trans-Yellow
        { 1139, 247 }, // Opal Trans-Yellow -> BL: Transparent Yellow Opal
        { 14, 3 }, // Yellow -> BL: Yellow
        { 1027, null }, // Modulex Light Yellow -> kein BL-Mapping
        { 18, 33 }, // Light Yellow -> BL: Light Yellow
        { 1117, null }, // HO Gold -> kein BL-Mapping
        { 1120, null }, // HO Light Gold -> kein BL-Mapping
        { 1028, null }, // Modulex Ochre Yellow -> kein BL-Mapping
        { 1048, null }, // Modulex Foil Yellow -> kein BL-Mapping
        { 82, 65 }, // Metallic Gold -> BL: Metallic Gold
        { 1020, null }, // Modulex Terracotta -> kein BL-Mapping
        { 191, 110 }, // Bright Light Orange -> BL: Bright Light Orange
        { 19, 2 }, // Tan -> BL: Tan
        { 1133, null }, // HO Tan -> kein BL-Mapping
        { 28, 69 }, // Dark Tan -> BL: Dark Tan
        { 297, 115 }, // Pearl Gold -> BL: Pearl Gold
        { 142, 61 }, // Pearl Light Gold -> BL: Pearl Light Gold
        { 462, 31 }, // Medium Orange -> BL: Medium Orange
        { 1022, null }, // Modulex Buff -> kein BL-Mapping
        { 308, 120 }, // Dark Brown -> BL: Dark Brown
        { 1066, 169 }, // Curry -> BL: Curry
        { 1091, 8 }, // Warm Yellowish Orange -> BL: Light Orange
        { 1080, null }, // Light Tan -> kein BL-Mapping
        { 1063, 227 }, // Pearl Copper -> BL: Reddish Copper
        { 366, 29 }, // Earth Orange -> BL: Earth Orange
        { 1145, 255 }, // Ochre Yellow -> BL: Ochre Yellow
        { 125, 32 }, // Light Orange -> BL: Light Orange
        { 1065, 235 }, // Reddish Gold -> BL: Reddish Gold
        { 68, 96 }, // Very Light Orange -> BL: Very Light Orange
        { 60, 110 }, // Chrome Antique Brass -> BL: Chrome Brass
        { 1116, null }, // HO Earth Orange -> kein BL-Mapping
        { 1021, null }, // Modulex Brown -> kein BL-Mapping
        { 182, 98 }, // Trans-Orange -> BL: Trans-Orange
        { 1052, 222 }, // Glitter Trans-Orange -> BL: Glitter Trans-Orange
        { 1012, 160 }, // Fabuland Orange -> BL: Fabuland Orange
        { 1089, 241 }, // Warm Tan -> BL: Medium Tan
        { 78, 90 }, // Light Nougat -> BL: Light Nougat
        { 1004, 164 }, // Trans-Flame Yellowish Orange -> BL: Trans Light Orange
        { 484, 68 }, // Dark Orange -> BL: Dark Orange
        { 25, 4 }, // Orange -> BL: Orange
        { 1049, null }, // Modulex Foil Orange -> kein BL-Mapping
        { 1026, null }, // Modulex Light Orange -> kein BL-Mapping
        { 178, 81 }, // Flat Dark Gold -> BL: Flat Dark Gold
        { 1085, 229 }, // Two-tone Silver -> BL: Bionicle Silver
        { 57, 18 }, // Trans-Neon Orange -> BL: Trans-Neon Orange
        { 1064, null }, // Fabuland Red -> kein BL-Mapping
        { 84, 150 }, // Medium Nougat -> BL: Medium Nougat
        { 450, 106 }, // Fabuland Brown -> BL: Fabuland Brown
        { 1088, 240 }, // Medium Brown -> BL: Medium Brown
        { 1084, 231 }, // Two-tone Gold -> BL: Bionicle Gold
        { 92, 28 }, // Nougat -> BL: Nougat
        { 1025, null }, // Modulex Orange -> kein BL-Mapping
        { 1137, 169 }, // Sienna Brown -> BL: Sienna
        { 6, 8 }, // Brown -> BL: Brown
        { 1056, 229 }, // Opal Trans-Brown -> BL: Satin Trans-Black
        { 134, 84 }, // Copper -> BL: Copper
        { 70, 88 }, // Reddish Brown -> BL: Reddish Brown
        { 1136, 167 }, // Reddish Orange -> BL: Reddish Orange
        { 86, 91 }, // Light Brown -> BL: Light Brown
        { 1119, null }, // HO Light Brown -> kein BL-Mapping
        { 1067, 225 }, // Dark Nougat -> BL: Dark Nougat
        { 1092, 250 }, // Metallic Copper -> BL: Metallic Copper
        { 1072, 219 }, // Pearl Brown -> BL: Pearl Brown
        { 1138, 168 }, // Umber Brown -> BL: Umber
        { 1140, null }, // Neon Orange -> kein BL-Mapping
        { 1081, 83 }, // Rust Orange -> BL: Rust
        { 1068, 158 }, // Bright Reddish Orange -> BL: Bright Reddish Orange
        { 1024, null }, // Modulex Pink Red -> kein BL-Mapping
        { 1010, null }, // Vintage Red -> kein BL-Mapping
        { 12, 25 }, // Salmon -> BL: Salmon
        { 1083, 233 }, // Two-tone Copper -> BL: Bionicle Copper
        { 4, 5 }, // Red -> BL: Red
        { 36, 17 }, // Trans-Red -> BL: Trans-Red
        { 1144, null }, // Chrome Red -> kein BL-Mapping
        { 216, 83 }, // Rust -> BL: Rust
        { 1023, null }, // Modulex Red -> kein BL-Mapping
        { 335, 58 }, // Sand Red -> BL: Sand Red
        { 1047, null }, // Modulex Foil Red -> kein BL-Mapping
        { 1019, null }, // Modulex Tile Brown -> kein BL-Mapping
        { 79, 60 }, // Milky White -> BL: Milky White
        { 47, 12 }, // Trans-Clear -> BL: Trans-Clear
        { 183, 83 }, // Pearl White -> BL: Pearl White
        { 1124, null }, // HO Medium Red -> kein BL-Mapping
        { 503, 49 }, // Very Light Gray -> BL: Very Light Gray
        { 151, 99 }, // Very Light Bluish Gray -> BL: Very Light Bluish Gray
        { 383, 22 }, // Chrome Silver -> BL: Chrome Silver
        { 21, 46 }, // Glow In Dark Opaque -> BL: Glow In Dark Opaque
        { 1135, null }, // Metal -> kein BL-Mapping
        { 80, 67 }, // Metallic Silver -> BL: Metallic Silver
        { 150, 119 }, // Pearl Very Light Gray -> BL: Pearl Very Light Gray
        { 71, 86 }, // Light Bluish Gray -> BL: Light Bluish Gray
        { 135, 66 }, // Pearl Light Gray -> BL: Pearl Light Gray
        { 7, 9 }, // Light Gray -> BL: Light Gray
        { 179, 95 }, // Flat Silver -> BL: Flat Silver
        { 1130, null }, // HO Rose -> kein BL-Mapping
        { 8, 10 }, // Dark Gray -> BL: Dark Gray
        { 72, 85 }, // Dark Bluish Gray -> BL: Dark Bluish Gray
        { 40, 13 }, // Trans-Brown -> BL: Trans-Black
        { 1095, 251 }, // Trans-Black -> BL: Trans-Black (2023)
        { 1016, null }, // Modulex Charcoal Gray -> kein BL-Mapping
        { 1040, null }, // Modulex Foil Dark Gray -> kein BL-Mapping
        { 148, 77 }, // Pearl Dark Gray -> BL: Pearl Dark Gray
        { 1103, 77 }, // Pearl Titanium -> BL: Pearl Dark Gray
        { 64, 111 }, // Chrome Black -> BL: Chrome Black
        { 1017, null }, // Modulex Tile Gray -> kein BL-Mapping
        { 133, 151 }, // Speckle Black-Gold -> BL: Speckle Black-Gold
        { 75, 116 }, // Speckle Black-Copper -> BL: Speckle Black-Copper
        { 132, 111 }, // Speckle Black-Silver -> BL: Speckle Black-Silver
        { 0, 11 }, // Black -> BL: Black
        { 117, 101 }, // Glitter Trans-Clear -> BL: Glitter Trans-Clear
        { 15, 1 }, // White -> BL: White
        { 1143, null }, // Glitter Milky White -> kein BL-Mapping
        { 1039, null }, // Modulex Clear -> kein BL-Mapping
        { 1055, 228 }, // Opal Trans-Clear -> BL: Satin White
        { 1013, null }, // Modulex White -> kein BL-Mapping
        { 1000, 159 }, // Glow in Dark White -> BL: Glow in Dark White
        { 1015, null }, // Modulex Light Gray -> kein BL-Mapping
        { 1041, null }, // Modulex Foil Light Gray -> kein BL-Mapping
        { 1134, null }, // HO Titanium -> kein BL-Mapping
        { 1126, null }, // HO Metallic Dark Gray -> kein BL-Mapping
    };

    /// <summary>
    /// Mapping Rebrickable-ID -> BrickOwl-ID. Null wenn keine BO-Entsprechung existiert.
    /// </summary>
    public static readonly IReadOnlyDictionary<int, int?> RebrickableToBrickOwl = new Dictionary<int, int?>
    {
        { 320, 56 }, // Dark Red -> BO: Dark Red
        { 1113, null }, // HO Dark Red -> kein BO-Mapping
        { 100, 5 }, // Light Salmon -> BO: Light Salmon
        { 77, 56 }, // Light Pink -> BO: Rose Pink
        { 1037, null }, // Modulex Violet -> kein BO-Mapping
        { 1146, 259 }, // Warm Pink -> BO: Warm Pink
        { 1087, null }, // Duplo Pink -> kein BO-Mapping
        { 1069, 181 }, // Pearl Red -> BO: Pearl Red
        { 13, 3 }, // Pink -> BO: Pink
        { 1102, null }, // Trans-Neon Red -> kein BO-Mapping
        { 1050, 173 }, // Coral -> BO: Coral
        { 351, 75 }, // Medium Dark Pink -> BO: Medium Dark Pink
        { 1038, null }, // Modulex Pink -> kein BO-Mapping
        { 114, 132 }, // Glitter Trans-Dark Pink -> BO: Transparent Pink Glitter
        { 45, 99 }, // Trans-Dark Pink -> BO: Transparent Dark Pink
        { 1082, null }, // Clikits Pink -> kein BO-Mapping
        { 69, 69 }, // Light Purple -> BO: Light Purple
        { 29, 45 }, // Bright Pink -> BO: Bright Pink
        { 230, 106 }, // Trans-Pink -> BO: Transparent Pink
        { 1099, null }, // Glitter Trans-Pink -> kein BO-Mapping
        { 5, 17 }, // Dark Pink -> BO: Dark Pink
        { 1054, 199 }, // Opal Trans-Dark Pink -> BO: Transparent Dark Pink Opal
        { 26, 72 }, // Magenta -> BO: Magenta
        { 63, null }, // Chrome Pink -> kein BO-Mapping
        { 22, 4 }, // Purple -> BO: Purple
        { 373, 86 }, // Sand Purple -> BO: Sand Purple
        { 1007, 223 }, // Reddish Lilac -> BO: Very Light Purple
        { 236, 114 }, // Trans-Light Purple -> BO: Trans-Light Purple
        { 30, 76 }, // Medium Lavender -> BO: Medium Lavender
        { 1059, 203 }, // Opal Trans-Purple -> BO: Transparent Purple Opal
        { 1046, null }, // Modulex Foil Violet -> kein BO-Mapping
        { 31, 36 }, // Lavender -> BO: Lavender
        { 1101, null }, // Duplo Dark Purple -> kein BO-Mapping
        { 1097, null }, // Glitter Trans-Medium Purple -> kein BO-Mapping
        { 1094, null }, // Trans-Medium Purple -> kein BO-Mapping
        { 1018, null }, // Modulex Black -> kein BO-Mapping
        { 85, 55 }, // Dark Purple -> BO: Dark Purple
        { 1001, 245 }, // Medium Violet -> BO: Lilac
        { 129, 22 }, // Glitter Trans-Purple -> BO: Transparent Purple Glitter
        { 52, 107 }, // Trans-Purple -> BO: Transparent Purple
        { 20, 16 }, // Light Violet -> BO: Light Violet
        { 1147, 257 }, // Blue Violet -> BO: Blue Violet
        { 1093, null }, // Light Lilac -> kein BO-Mapping
        { 23, 49 }, // Dark Blue-Violet -> BO: Dark Royal Blue
        { 112, 78 }, // Medium Bluish Violet -> BO: Medium Violet
        { 89, 40 }, // Royal Blue -> BO: Royal Blue
        { 1061, 209 }, // Opal Trans-Dark Blue -> BO: Transparent Dark Blue Opal
        { 33, 98 }, // Trans-Dark Blue -> BO: Transparent Dark Blue
        { 110, 15 }, // Violet -> BO: Violet
        { 1014, null }, // Modulex Light Bluish Gray -> kein BO-Mapping
        { 1073, 185 }, // Pearl Black -> BO: Pearl Black
        { 379, 85 }, // Sand Blue -> BO: Sand Blue
        { 137, 118 }, // Pearl Sand Blue -> BO: Metallic Blue
        { 1123, null }, // HO Medium Blue -> kein BO-Mapping
        { 1, 39 }, // Blue -> BO: Blue
        { 73, 14 }, // Medium Blue -> BO: Medium Blue
        { 272, 48 }, // Dark Blue -> BO: Dark Blue
        { 1109, null }, // HO Dark Blue -> kein BO-Mapping
        { 1006, null }, // Trans-Light Royal Blue -> kein BO-Mapping
        { 143, 102 }, // Trans-Medium Blue -> BO: Transparent Medium Blue
        { 1035, null }, // Modulex Medium Blue -> kein BO-Mapping
        { 1131, null }, // HO Sand Blue -> kein BO-Mapping
        { 212, 42 }, // Bright Light Blue -> BO: Bright Light Blue
        { 1034, null }, // Modulex Tile Blue -> kein BO-Mapping
        { 1044, null }, // Modulex Foil Dark Blue -> kein BO-Mapping
        { 61, null }, // Chrome Blue -> kein BO-Mapping
        { 1070, 189 }, // Pearl Blue -> BO: Pearl Blue
        { 9, 63 }, // Light Blue -> BO: Light Blue
        { 43, 25 }, // Trans-Very Lt Blue -> BO: Transparent Very Light Blue
        { 313, null }, // Maersk Blue -> kein BO-Mapping
        { 1128, null }, // HO Metallic Sand Blue -> kein BO-Mapping
        { 321, 47 }, // Dark Azure -> BO: Dark Azure
        { 1105, null }, // HO Azure -> kein BO-Mapping
        { 1125, null }, // HO Metallic Blue -> kein BO-Mapping
        { 1045, null }, // Modulex Foil Light Blue -> kein BO-Mapping
        { 1036, null }, // Modulex Pastel Blue -> kein BO-Mapping
        { 1107, null }, // HO Cyan -> kein BO-Mapping
        { 1033, null }, // Modulex Teal Blue -> kein BO-Mapping
        { 232, 88 }, // Sky Blue -> BO: Sky Blue
        { 1106, null }, // HO Blue-gray -> kein BO-Mapping
        { 1075, null }, // Duplo Medium Blue -> kein BO-Mapping
        { 1074, null }, // Duplo Blue -> kein BO-Mapping
        { 1008, null }, // Vintage Blue -> kein BO-Mapping
        { 1051, null }, // Pastel Blue -> kein BO-Mapping
        { 322, 73 }, // Medium Azure -> BO: Medium Azure
        { 11, 12 }, // Light Turquoise -> BO: Light Turquoise
        { 1003, 165 }, // Glitter Trans-Light Blue -> BO: Transparent Light Blue Glitter
        { 1053, 175 }, // Opal Trans-Light Blue -> BO: Transparent Blue Opal
        { 3, 58 }, // Dark Turquoise -> BO: Dark Turquoise
        { 1115, null }, // HO Dark Turquoise -> kein BO-Mapping
        { 41, 101 }, // Trans-Light Blue -> BO: Transparent Light Blue
        { 1032, null }, // Modulex Aqua Green -> kein BO-Mapping
        { 323, 62 }, // Light Aqua -> BO: Light Aqua
        { 1104, null }, // HO Aqua -> kein BO-Mapping
        { 118, 13 }, // Aqua -> BO: Aqua
        { 1090, null }, // Duplo Turquoise -> kein BO-Mapping
        { 1108, null }, // HO Dark Aqua -> kein BO-Mapping
        { 1118, null }, // HO Light Aqua -> kein BO-Mapping
        { 1111, null }, // HO Dark Green -> kein BO-Mapping
        { 288, 20 }, // Dark Green -> BO: Dark Green
        { 62, null }, // Chrome Green -> kein BO-Mapping
        { 74, 10 }, // Medium Green -> BO: Medium Green
        { 1071, 183 }, // Pearl Green -> BO: Pearl Green
        { 378, 18 }, // Sand Green -> BO: Sand Green
        { 1132, null }, // HO Sand Green -> kein BO-Mapping
        { 1078, null }, // Duplo Medium Green -> kein BO-Mapping
        { 2, 61 }, // Green -> BO: Green
        { 1058, 191 }, // Trans-Light Green -> BO: Transparent Light Green
        { 1079, null }, // Duplo Light Green -> kein BO-Mapping
        { 1098, null }, // Glitter Trans-Green -> kein BO-Mapping
        { 34, 100 }, // Trans-Green -> BO: Transparent Green
        { 1060, 207 }, // Opal Trans-Bright Green -> BO: Transparent Green Opal
        { 1042, null }, // Modulex Foil Dark Green -> kein BO-Mapping
        { 1009, null }, // Vintage Green -> kein BO-Mapping
        { 1077, null }, // Fabuland Lime -> kein BO-Mapping
        { 1114, null }, // HO Dark Sand Green -> kein BO-Mapping
        { 10, 41 }, // Bright Green -> BO: Bright Green
        { 17, 11 }, // Light Green -> BO: Light Green
        { 1043, null }, // Modulex Foil Light Green -> kein BO-Mapping
        { 1030, null }, // Modulex Pastel Green -> kein BO-Mapping
        { 294, 128 }, // Glow In Dark Trans -> BO: Glow in the Dark Transparent
        { 1127, null }, // HO Metallic Green -> kein BO-Mapping
        { 76, 134 }, // Speckle DBGray-Silver -> BO: Speckle Gray
        { 1031, null }, // Modulex Olive Green -> kein BO-Mapping
        { 1057, 205 }, // Trans-Light Bright Green -> BO: Transparent Light Bright Green
        { 1086, null }, // Pearl Lime -> kein BO-Mapping
        { 81, null }, // Metallic Green -> kein BO-Mapping
        { 1002, 167 }, // Glitter Trans-Neon Green -> BO: Transparent Neon Green Glitter
        { 1141, null }, // Neon Green -> kein BO-Mapping
        { 27, 70 }, // Lime -> BO: Lime
        { 158, 94 }, // Yellowish Green -> BO: Yellowish Green
        { 120, 67 }, // Light Lime -> BO: Light Lime
        { 35, 96 }, // Trans-Bright Green -> BO: Transparent Bright Green
        { 115, 77 }, // Medium Lime -> BO: Medium Lime
        { 1122, null }, // HO Light Yellow -> kein BO-Mapping
        { 1029, null }, // Modulex Lemon -> kein BO-Mapping
        { 1112, null }, // HO Dark Lime -> kein BO-Mapping
        { 1110, null }, // HO Dark Gray -> kein BO-Mapping
        { 1129, null }, // HO Olive Green -> kein BO-Mapping
        { 326, 79 }, // Olive Green -> BO: Olive Green
        { 1142, null }, // Dark Olive Green -> kein BO-Mapping
        { 1076, null }, // Duplo Lime -> kein BO-Mapping
        { 42, 103 }, // Trans-Neon Green -> BO: Transparent Neon Green
        { 1062, 211 }, // Vibrant Yellow -> BO: Vibrant Yellow
        { 226, 44 }, // Bright Light Yellow -> BO: Bright Light Yellow
        { 1121, null }, // HO Light Tan -> kein BO-Mapping
        { 334, 2 }, // Chrome Gold -> BO: Chrome Gold
        { 1005, null }, // Trans-Fire Yellow -> kein BO-Mapping
        { 54, 104 }, // Trans-Neon Yellow -> BO: Transparent Neon Yellow
        { 1011, null }, // Vintage Yellow -> kein BO-Mapping
        { 1100, null }, // Clikits Yellow -> kein BO-Mapping
        { 46, 109 }, // Trans-Yellow -> BO: Transparent Yellow
        { 1139, null }, // Opal Trans-Yellow -> kein BO-Mapping
        { 14, 93 }, // Yellow -> BO: Yellow
        { 1027, null }, // Modulex Light Yellow -> kein BO-Mapping
        { 18, 9 }, // Light Yellow -> BO: Light Yellow
        { 1117, null }, // HO Gold -> kein BO-Mapping
        { 1120, null }, // HO Light Gold -> kein BO-Mapping
        { 1028, null }, // Modulex Ochre Yellow -> kein BO-Mapping
        { 1048, null }, // Modulex Foil Yellow -> kein BO-Mapping
        { 82, 124 }, // Metallic Gold -> BO: Metallic Gold
        { 1020, null }, // Modulex Terracotta -> kein BO-Mapping
        { 191, 43 }, // Bright Light Orange -> BO: Bright Light Orange
        { 19, 89 }, // Tan -> BO: Tan
        { 1133, null }, // HO Tan -> kein BO-Mapping
        { 28, 57 }, // Dark Tan -> BO: Dark Tan
        { 297, 120 }, // Pearl Gold -> BO: Pearl Gold
        { 142, 121 }, // Pearl Light Gold -> BO: Pearl Light Gold
        { 462, 7 }, // Medium Orange -> BO: Medium Orange
        { 1022, null }, // Modulex Buff -> kein BO-Mapping
        { 308, 51 }, // Dark Brown -> BO: Dark Brown
        { 1066, null }, // Curry -> kein BO-Mapping
        { 1091, null }, // Warm Yellowish Orange -> kein BO-Mapping
        { 1080, null }, // Light Tan -> kein BO-Mapping
        { 1063, null }, // Pearl Copper -> kein BO-Mapping
        { 366, 59 }, // Earth Orange -> BO: Earth Orange
        { 1145, null }, // Ochre Yellow -> kein BO-Mapping
        { 125, 8 }, // Light Orange -> BO: Light Orange
        { 1065, 215 }, // Reddish Gold -> BO: Reddish Gold
        { 68, 91 }, // Very Light Orange -> BO: Very Light Orange
        { 60, null }, // Chrome Antique Brass -> kein BO-Mapping
        { 1116, null }, // HO Earth Orange -> kein BO-Mapping
        { 1021, null }, // Modulex Brown -> kein BO-Mapping
        { 182, 105 }, // Trans-Orange -> BO: Transparent Orange
        { 1052, 179 }, // Glitter Trans-Orange -> BO: Transparent Orange with Glitter
        { 1012, 60 }, // Fabuland Orange -> BO: Fabuland Orange
        { 1089, 217 }, // Warm Tan -> BO: Warm Tan
        { 78, 65 }, // Light Nougat -> BO: Light Flesh
        { 1004, 171 }, // Trans-Flame Yellowish Orange -> BO: Transparent Light Orange
        { 484, 54 }, // Dark Orange -> BO: Dark Orange
        { 25, 80 }, // Orange -> BO: Orange
        { 1049, null }, // Modulex Foil Orange -> kein BO-Mapping
        { 1026, null }, // Modulex Light Orange -> kein BO-Mapping
        { 178, 21 }, // Flat Dark Gold -> BO: Flat Dark Gold
        { 1085, null }, // Two-tone Silver -> kein BO-Mapping
        { 57, 161 }, // Trans-Neon Orange -> BO: Transparent Neon Reddish Orange
        { 1064, null }, // Fabuland Red -> kein BO-Mapping
        { 84, 74 }, // Medium Nougat -> BO: Medium Dark Flesh
        { 450, 23 }, // Fabuland Brown -> BO: Fabuland Brown
        { 1088, 213 }, // Medium Brown -> BO: Medium Brown
        { 1084, null }, // Two-tone Gold -> kein BO-Mapping
        { 92, 6 }, // Nougat -> BO: Flesh
        { 1025, null }, // Modulex Orange -> kein BO-Mapping
        { 1137, 245 }, // Sienna Brown -> BO: Sienna Brown
        { 6, 46 }, // Brown -> BO: Brown
        { 1056, 201 }, // Opal Trans-Brown -> BO: Transparent Black Opal
        { 134, 116 }, // Copper -> BO: Copper
        { 70, 82 }, // Reddish Brown -> BO: Reddish Brown
        { 1136, 241 }, // Reddish Orange -> BO: Reddish Orange
        { 86, 52 }, // Light Brown -> BO: Dark Flesh
        { 1119, null }, // HO Light Brown -> kein BO-Mapping
        { 1067, 160 }, // Dark Nougat -> BO: Dark Nougat
        { 1092, 225 }, // Metallic Copper -> BO: Metallic Copper
        { 1072, null }, // Pearl Brown -> kein BO-Mapping
        { 1138, 243 }, // Umber Brown -> BO: Umber Brown
        { 1140, null }, // Neon Orange -> kein BO-Mapping
        { 1081, null }, // Rust Orange -> kein BO-Mapping
        { 1068, null }, // Bright Reddish Orange -> kein BO-Mapping
        { 1024, null }, // Modulex Pink Red -> kein BO-Mapping
        { 1010, null }, // Vintage Red -> kein BO-Mapping
        { 12, 84 }, // Salmon -> BO: Salmon
        { 1083, null }, // Two-tone Copper -> kein BO-Mapping
        { 4, 81 }, // Red -> BO: Red
        { 36, 108 }, // Trans-Red -> BO: Transparent Red
        { 1144, null }, // Chrome Red -> kein BO-Mapping
        { 216, null }, // Rust -> kein BO-Mapping
        { 1023, null }, // Modulex Red -> kein BO-Mapping
        { 335, 87 }, // Sand Red -> BO: Sand Red
        { 1047, null }, // Modulex Foil Red -> kein BO-Mapping
        { 1019, null }, // Modulex Tile Brown -> kein BO-Mapping
        { 79, 130 }, // Milky White -> BO: Translucent White
        { 47, 97 }, // Trans-Clear -> BO: Transparent
        { 183, 123 }, // Pearl White -> BO: Pearlescent
        { 1124, null }, // HO Medium Red -> kein BO-Mapping
        { 503, 19 }, // Very Light Gray -> BO: Very Light Gray
        { 151, 90 }, // Very Light Bluish Gray -> BO: Light Stone Gray
        { 383, 115 }, // Chrome Silver -> BO: Chrome Silver
        { 21, 127 }, // Glow In Dark Opaque -> BO: Glow in the Dark Opaque
        { 1135, null }, // Metal -> kein BO-Mapping
        { 80, 126 }, // Metallic Silver -> BO: Metallic Silver
        { 150, 27 }, // Pearl Very Light Gray -> BO: Pearl Very Light Gray
        { 71, 64 }, // Light Bluish Gray -> BO: Medium Stone Gray
        { 135, 122 }, // Pearl Light Gray -> BO: Pearl Light Gray
        { 7, 66 }, // Light Gray -> BO: Light Gray
        { 179, 117 }, // Flat Silver -> BO: Flat Silver
        { 1130, null }, // HO Rose -> kein BO-Mapping
        { 8, 53 }, // Dark Gray -> BO: Dark Gray
        { 72, 50 }, // Dark Bluish Gray -> BO: Dark Stone Gray
        { 40, 95 }, // Trans-Brown -> BO: Transparent Black
        { 1095, 235 }, // Trans-Black -> BO: Transparent Black (New)
        { 1016, null }, // Modulex Charcoal Gray -> kein BO-Mapping
        { 1040, null }, // Modulex Foil Dark Gray -> kein BO-Mapping
        { 148, 119 }, // Pearl Dark Gray -> BO: Pearl Dark Gray
        { 1103, 119 }, // Pearl Titanium -> BO: Pearl Dark Gray
        { 64, null }, // Chrome Black -> kein BO-Mapping
        { 1017, null }, // Modulex Tile Gray -> kein BO-Mapping
        { 133, 35 }, // Speckle Black-Gold -> BO: Speckle Black Gold
        { 75, 133 }, // Speckle Black-Copper -> BO: Speckle Black Copper
        { 132, 24 }, // Speckle Black-Silver -> BO: Speckle Black
        { 0, 38 }, // Black -> BO: Black
        { 117, 131 }, // Glitter Trans-Clear -> BO: Transparent Glitter
        { 15, 92 }, // White -> BO: White
        { 1143, null }, // Glitter Milky White -> kein BO-Mapping
        { 1039, null }, // Modulex Clear -> kein BO-Mapping
        { 1055, 193 }, // Opal Trans-Clear -> BO: Transparent Opal
        { 1013, null }, // Modulex White -> kein BO-Mapping
        { 1000, 129 }, // Glow in Dark White -> BO: Glow in the Dark White
        { 1015, null }, // Modulex Light Gray -> kein BO-Mapping
        { 1041, null }, // Modulex Foil Light Gray -> kein BO-Mapping
        { 1134, null }, // HO Titanium -> kein BO-Mapping
        { 1126, null }, // HO Metallic Dark Gray -> kein BO-Mapping
    };

    /// <summary>
    /// BrickLink-Farb-Namen. BL-IDs koennen sich mit Rebrickable ueberschneiden,
    /// daher ist diese Tabelle nach BL-ID indiziert.
    /// </summary>
    public static readonly IReadOnlyDictionary<int, string> BricklinkColorNames = new Dictionary<int, string>
    {
        { 59, "Dark Red" },
        { 26, "Light Salmon" },
        { 77, "Light_Pink" },
        { 175, "Warm Pink" },
        { 252, "Pearl Red" },
        { 23, "Pink" },
        { 220, "Coral" },
        { 94, "Medium Dark Pink" },
        { 100, "Glitter Trans-Dark Pink" },
        { 50, "Trans-Dark Pink" },
        { 93, "Light Purple" },
        { 104, "Bright Pink" },
        { 107, "Trans-Pink" },
        { 47, "Dark Pink" },
        { 224, "Satin Trans-Dark Pink" },
        { 71, "Magenta" },
        { 114, "Chrome Pink" },
        { 24, "Purple" },
        { 54, "Sand Purple" },
        { 227, "Clikits Lavender" },
        { 284, "Trans_Light_Purple" },
        { 157, "Medium Lavender" },
        { 230, "Satin Trans-Purple" },
        { 154, "Lavender" },
        { 89, "Dark Purple" },
        { 112, "Medium_Violet" },
        { 102, "Glitter Trans-Purple" },
        { 51, "Trans-Purple" },
        { 44, "Light Violet" },
        { 174, "Blue Violet" },
        { 16, "Light Violet" },
        { 109, "Dark Blue-Violet" },
        { 73, "Medium Violet" },
        { 97, "Royal Blue" },
        { 232, "Satin Trans-Dark Blue" },
        { 14, "Trans-Dark Blue" },
        { 43, "Violet" },
        { 244, "Pearl Black" },
        { 55, "Sand Blue" },
        { 78, "Pearl Sand Blue" },
        { 7, "Blue" },
        { 42, "Medium Blue" },
        { 63, "Dark Blue" },
        { 163, "Transparent Light Royal Blue" },
        { 74, "Trans-Medium Blue" },
        { 105, "Bright Light Blue" },
        { 254, "Pearl Blue" },
        { 62, "Light Blue" },
        { 113, "Trans-Aqua" },
        { 153, "Dark Azure" },
        { 87, "Sky Blue" },
        { 156, "Medium Azure" },
        { 40, "Light Turquoise" },
        { 162, "Glitter Trans-Light Blue" },
        { 223, "Satin Trans-Light Blue" },
        { 39, "Dark Turquoise" },
        { 15, "Trans-Light Blue" },
        { 152, "Light Aqua" },
        { 41, "Aqua" },
        { 80, "Dark Green" },
        { 37, "Medium Green" },
        { 253, "Pearl Green" },
        { 48, "Sand Green" },
        { 6, "Green" },
        { 221, "Trans-Light Green" },
        { 20, "Trans-Green" },
        { 233, "Satin Trans-Bright Green" },
        { 248, "Fabuland Lime" },
        { 36, "Bright Green" },
        { 38, "Light Green" },
        { 118, "Glow In Dark Trans" },
        { 117, "Speckle DBGray-Silver" },
        { 226, "Trans-Light Bright Green" },
        { 125, "Metallic Green" },
        { 34, "Lime" },
        { 158, "Yellowish Green" },
        { 35, "Light Lime" },
        { 108, "Trans-Bright Green" },
        { 76, "Medium Lime" },
        { 155, "Olive Green" },
        { 67, "Light Lime" },
        { 236, "Neon Yellow" },
        { 103, "Bright Light Yellow" },
        { 21, "Chrome Gold" },
        { 121, "Trans-Neon Yellow" },
        { 19, "Trans-Yellow" },
        { 247, "Transparent Yellow Opal" },
        { 3, "Yellow" },
        { 33, "Light Yellow" },
        { 65, "Metallic Gold" },
        { 110, "Bright Light Orange" },
        { 2, "Tan" },
        { 69, "Dark Tan" },
        { 115, "Pearl Gold" },
        { 61, "Pearl Light Gold" },
        { 31, "Medium Orange" },
        { 120, "Dark Brown" },
        { 169, "Curry" },
        { 8, "Light Orange" },
        { 29, "Earth Orange" },
        { 255, "Ochre Yellow" },
        { 32, "Light Orange" },
        { 235, "Reddish Gold" },
        { 96, "Very Light Orange" },
        { 98, "Trans-Orange" },
        { 222, "Glitter Trans-Orange" },
        { 160, "Fabuland Orange" },
        { 241, "Medium Tan" },
        { 90, "Light Nougat" },
        { 164, "Trans Light Orange" },
        { 68, "Dark Orange" },
        { 4, "Orange" },
        { 81, "Flat Dark Gold" },
        { 229, "Bionicle Silver" },
        { 18, "Trans-Neon Orange" },
        { 150, "Medium Nougat" },
        { 106, "Fabuland Brown" },
        { 240, "Medium Brown" },
        { 231, "Bionicle Gold" },
        { 28, "Nougat" },
        { 84, "Copper" },
        { 88, "Reddish Brown" },
        { 167, "Reddish Orange" },
        { 91, "Light Brown" },
        { 225, "Dark Nougat" },
        { 250, "Metallic Copper" },
        { 219, "Pearl Brown" },
        { 168, "Umber" },
        { 83, "Rust" },
        { 25, "Salmon" },
        { 5, "Red" },
        { 17, "Trans-Red" },
        { 58, "Sand Red" },
        { 60, "Milky White" },
        { 12, "Trans-Clear" },
        { 49, "Very Light Gray" },
        { 99, "Very Light Bluish Gray" },
        { 22, "Chrome Silver" },
        { 46, "Glow In Dark Opaque" },
        { 119, "Pearl Very Light Gray" },
        { 86, "Light Bluish Gray" },
        { 66, "Pearl Light Gray" },
        { 9, "Light Gray" },
        { 95, "Flat Silver" },
        { 10, "Dark Gray" },
        { 85, "Dark Bluish Gray" },
        { 13, "Trans-Black" },
        { 251, "Trans-Black (2023)" },
        { 111, "Chrome Black" },
        { 151, "Speckle Black-Gold" },
        { 116, "Speckle Black-Copper" },
        { 11, "Black" },
        { 101, "Glitter Trans-Clear" },
        { 1, "White" },
        { 228, "Satin White" },
        { 159, "Glow in Dark White" },
    };

    /// <summary>
    /// Holt die BrickLink-Farb-ID fuer eine Rebrickable-Farb-ID.
    /// Returns false wenn keine Entsprechung gefunden wurde.
    /// </summary>
    public static bool TryGetBricklinkId(int rebrickableId, out int bricklinkId)
    {
        bricklinkId = 0;
        if (RebrickableToBricklink.TryGetValue(rebrickableId, out var bl) && bl.HasValue)
        {
            bricklinkId = bl.Value;
            return true;
        }
        return false;
    }

    /// <summary>
    /// Holt den BrickLink-Farbnamen fuer eine Rebrickable-Farb-ID.
    /// Returns null wenn keine Entsprechung gefunden wurde.
    /// </summary>
    public static string? GetBricklinkColorName(int rebrickableId)
    {
        if (TryGetBricklinkId(rebrickableId, out var blId))
        {
            if (BricklinkColorNames.TryGetValue(blId, out var name))
            {
                return name;
            }
        }
        return null;
    }

    /// <summary>
    /// Holt die BrickOwl-Farb-ID fuer eine Rebrickable-Farb-ID.
    /// Returns false wenn keine Entsprechung gefunden wurde.
    /// </summary>
    public static bool TryGetBrickOwlId(int rebrickableId, out int brickOwlId)
    {
        brickOwlId = 0;
        if (RebrickableToBrickOwl.TryGetValue(rebrickableId, out var bo) && bo.HasValue)
        {
            brickOwlId = bo.Value;
            return true;
        }
        return false;
    }
}